# Introduction to Reinforcement Learning & OpenAI Gym

<img src="https://upload.wikimedia.org/wikipedia/commons/1/1b/Reinforcement_learning_diagram.svg">



# Installation:

<img width="70px" src="https://gym.openai.com/assets/dist/home/header/home-icon-54c30e2345.svg">

### Install  <a hraf="https://openai.com/">OpenAI</a>  <a hraf="https://gym.openai.com/">Gym</a> using pip

`pip install gym`


In [1]:
import gym #import gym

### Creating Environment

In [2]:
env = gym.make("CartPole-v0")

In [3]:
obs = env.reset() # observation
print(obs)

[ 0.04825853 -0.03882399  0.04027655 -0.01669069]


In [4]:
env = gym.make("CartPole-v0")

def policy(obs):
    return 0 if obs[2] < 0 else 1

total_episode = 20
total_step = 1000
total_reward = []

for episode in range(total_episode):
    rewards = 0
    obs = env.reset()
    for step in range(total_step): 
        env.render()
        action = policy(obs)
        obs, reward, done, info = env.step(action)
        rewards += reward
        if done:
            break
        print("Reward", rewards, " after ", step + 1, "episodes")
        
env.close()

Reward 1.0  after  1 episodes
Reward 2.0  after  2 episodes
Reward 3.0  after  3 episodes
Reward 4.0  after  4 episodes
Reward 5.0  after  5 episodes
Reward 6.0  after  6 episodes
Reward 7.0  after  7 episodes
Reward 8.0  after  8 episodes
Reward 9.0  after  9 episodes
Reward 10.0  after  10 episodes
Reward 11.0  after  11 episodes
Reward 12.0  after  12 episodes
Reward 13.0  after  13 episodes
Reward 14.0  after  14 episodes
Reward 15.0  after  15 episodes
Reward 16.0  after  16 episodes
Reward 17.0  after  17 episodes
Reward 18.0  after  18 episodes
Reward 19.0  after  19 episodes
Reward 20.0  after  20 episodes
Reward 21.0  after  21 episodes
Reward 22.0  after  22 episodes
Reward 23.0  after  23 episodes
Reward 24.0  after  24 episodes
Reward 25.0  after  25 episodes
Reward 26.0  after  26 episodes
Reward 27.0  after  27 episodes
Reward 28.0  after  28 episodes
Reward 29.0  after  29 episodes
Reward 30.0  after  30 episodes
Reward 31.0  after  31 episodes
Reward 32.0  after  32 epi

Reward 23.0  after  23 episodes
Reward 24.0  after  24 episodes
Reward 25.0  after  25 episodes
Reward 26.0  after  26 episodes
Reward 27.0  after  27 episodes
Reward 28.0  after  28 episodes
Reward 29.0  after  29 episodes
Reward 30.0  after  30 episodes
Reward 31.0  after  31 episodes
Reward 32.0  after  32 episodes
Reward 33.0  after  33 episodes
Reward 34.0  after  34 episodes
Reward 35.0  after  35 episodes
Reward 36.0  after  36 episodes
Reward 37.0  after  37 episodes
Reward 38.0  after  38 episodes
Reward 39.0  after  39 episodes
Reward 40.0  after  40 episodes
Reward 41.0  after  41 episodes
Reward 42.0  after  42 episodes
Reward 43.0  after  43 episodes
Reward 44.0  after  44 episodes
Reward 45.0  after  45 episodes
Reward 46.0  after  46 episodes
Reward 1.0  after  1 episodes
Reward 2.0  after  2 episodes
Reward 3.0  after  3 episodes
Reward 4.0  after  4 episodes
Reward 5.0  after  5 episodes
Reward 6.0  after  6 episodes
Reward 7.0  after  7 episodes
Reward 8.0  after  8 e

Reward 2.0  after  2 episodes
Reward 3.0  after  3 episodes
Reward 4.0  after  4 episodes
Reward 5.0  after  5 episodes
Reward 6.0  after  6 episodes
Reward 7.0  after  7 episodes
Reward 8.0  after  8 episodes
Reward 9.0  after  9 episodes
Reward 10.0  after  10 episodes
Reward 11.0  after  11 episodes
Reward 12.0  after  12 episodes
Reward 13.0  after  13 episodes
Reward 14.0  after  14 episodes
Reward 15.0  after  15 episodes
Reward 16.0  after  16 episodes
Reward 17.0  after  17 episodes
Reward 18.0  after  18 episodes
Reward 19.0  after  19 episodes
Reward 20.0  after  20 episodes
Reward 21.0  after  21 episodes
Reward 22.0  after  22 episodes
Reward 23.0  after  23 episodes
Reward 24.0  after  24 episodes
Reward 25.0  after  25 episodes
Reward 26.0  after  26 episodes
Reward 27.0  after  27 episodes
Reward 28.0  after  28 episodes
Reward 29.0  after  29 episodes
Reward 30.0  after  30 episodes
Reward 31.0  after  31 episodes
Reward 32.0  after  32 episodes
Reward 33.0  after  33 e

Reward 1.0  after  1 episodes
Reward 2.0  after  2 episodes
Reward 3.0  after  3 episodes
Reward 4.0  after  4 episodes
Reward 5.0  after  5 episodes
Reward 6.0  after  6 episodes
Reward 7.0  after  7 episodes
Reward 8.0  after  8 episodes
Reward 9.0  after  9 episodes
Reward 10.0  after  10 episodes
Reward 11.0  after  11 episodes
Reward 12.0  after  12 episodes
Reward 13.0  after  13 episodes
Reward 14.0  after  14 episodes
Reward 15.0  after  15 episodes
Reward 16.0  after  16 episodes
Reward 17.0  after  17 episodes
Reward 18.0  after  18 episodes
Reward 19.0  after  19 episodes
Reward 20.0  after  20 episodes
Reward 21.0  after  21 episodes
Reward 22.0  after  22 episodes
Reward 23.0  after  23 episodes
Reward 24.0  after  24 episodes
Reward 25.0  after  25 episodes
Reward 26.0  after  26 episodes
Reward 27.0  after  27 episodes
Reward 28.0  after  28 episodes
Reward 29.0  after  29 episodes
Reward 30.0  after  30 episodes
Reward 31.0  after  31 episodes
Reward 32.0  after  32 epi

In [5]:
env = gym.make('MountainCar-v0')
for _ in range(20):
    obs = env.reset()
    for step in range(1000):
        env.render()
        print(obs)
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        if done:
            print("Reward", rewards, " after ", step + 1, "episodes")
            break
env.close()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[-0.48919594  0.        ]
[-0.4904535  -0.00125756]
[-0.49195925 -0.00150574]
[-0.49470193 -0.00274268]
[-0.49766107 -0.00295914]
[-0.50081455 -0.00315348]
[-0.50313877 -0.00232422]
[-0.50661635 -0.00347758]
[-0.50922124 -0.00260489]
[-0.51293393 -0.00371269]
[-0.51772659 -0.00479266]
[-0.52356329 -0.0058367 ]
[-0.52840026 -0.00483697]
[-0.53320121 -0.00480096]
[-0.53693016 -0.00372895]
[-0.53955915 -0.00262899]
[-0.54306849 -0.00350933]
[-0.54643188 -0.00336339]
[-0.54962416 -0.00319228]
[-0.55262144 -0.00299729]
[-0.55540134 -0.00277989]
[-0.55894307 -0.00354173]
[-0.56222022 -0.00327715]
[-0.56620835 -0.00398814]
[-0.57087779 -0.00466943]
[-0.57519381 -0.00431603]
[-0.57812442 -0.00293061]
[-0.58164791 -0.00352349]
[-0.58373823 -0.00209032]
[-0.58637994 -0.00264171]
[-0.58855357 -0.00217363]
[-0.59024312 -0.00168955]
[-5.90436163e-01 -1.93040532e-04]
[-0.59113128 -0.00069511]
[-5.91323

[-0.41892511 -0.00868582]
[-0.42738315 -0.00845804]
[-0.43755282 -0.01016968]
[-0.4493607  -0.01180788]
[-0.46172077 -0.01236007]
[-0.47354226 -0.01182149]
[-0.48573777 -0.01219551]
[-0.49921663 -0.01347886]
[-0.51387819 -0.01466156]
[-0.52961264 -0.01573445]
[-0.546302   -0.01668935]
[-0.56382121 -0.01751921]
[-0.58103948 -0.01721827]
[-0.59882908 -0.0177896 ]
[-0.61505922 -0.01623015]
[-0.62961199 -0.01455277]
[-0.642383   -0.01277101]
[-0.65528186 -0.01289886]
[-0.66821858 -0.01293673]
[-0.67910437 -0.01088579]
[-0.68986571 -0.01076134]
[-0.69843112 -0.00856541]
[-0.70474458 -0.00631347]
[-0.71076535 -0.00602076]
[-0.71545497 -0.00468962]
[-0.71878381 -0.00332884]
[-0.720731   -0.00194719]
[-0.72228438 -0.00155338]
[-0.7234343  -0.00114992]
[-7.23173641e-01  2.60663179e-04]
[-7.22504005e-01  6.69636626e-04]
[-0.72142955  0.00107446]
[-0.71895694  0.00247261]
[-0.71410159  0.00485534]
[-0.706894   0.0072076]
[-0.69937992  0.00751407]
[-0.68960775  0.00977217]
[-0.67864135  0.0109664 

[-0.43769924  0.00485013]
[-0.43248625  0.00521299]
[-0.42694812  0.00553813]
[-0.42112476  0.00582336]
[-0.4150579   0.00606686]
[-0.41079079  0.00426711]
[-0.40735368  0.00343711]
[-0.40477085  0.00258283]
[-0.40206047  0.00271038]
[-0.39924156  0.00281891]
[-0.39633385  0.00290771]
[-0.3943576   0.00197625]
[-0.39332656  0.00103104]
[-3.93247879e-01  7.86825595e-05]
[-3.93122101e-01  1.25777946e-04]
[-3.92950100e-01  1.72001279e-04]
[-0.39373307 -0.00078297]
[-0.39446557 -0.00073251]
[-0.39714254 -0.00267696]
[-0.40074533 -0.0036028 ]
[-0.40524881 -0.00450348]
[-0.40962139 -0.00437257]
[-0.41583223 -0.00621084]
[-0.42283731 -0.00700508]
[-0.43158665 -0.00874934]
[-0.44201735 -0.0104307 ]
[-0.45205382 -0.01003647]
[-0.46262277 -0.01056895]
[-0.47464649 -0.01202372]
[-0.48703604 -0.01238954]
[-0.49869925 -0.01166322]
[-0.51054904 -0.01184979]
[-0.52149668 -0.01094764]
[-0.53246008 -0.0109634 ]
[-0.54335703 -0.01089695]
[-0.55310588 -0.00974885]
[-0.56363372 -0.01052784]
[-0.57486201 -

[-0.44097868  0.00938801]
[-0.43220399  0.00877469]
[-0.42510621  0.00709778]
[-0.41973642  0.00536979]
[-0.41413305  0.00560337]
[-0.409336    0.00479705]
[-0.40437923  0.00495677]
[-0.39929767  0.00508156]
[-0.39512691  0.00417076]
[-0.39189601  0.0032309 ]
[-0.38862739  0.00326863]
[-0.38734361  0.00128378]
[-0.38605352  0.00129009]
[-0.386766   -0.00071248]
[-0.38947614 -0.00271014]
[-0.39216528 -0.00268914]
[-0.39581482 -0.00364954]
[-0.39939945 -0.00358462]
[-0.40289416 -0.00349471]
[-0.4082745  -0.00538034]
[-0.41350263 -0.00522812]
[-0.41954154 -0.00603891]
[-0.42534827 -0.00580673]
[-0.43088125 -0.00553298]
[-0.43810068 -0.00721943]
[-0.44595434 -0.00785366]
[-0.45438508 -0.00843074]
[-0.4643312  -0.00994612]
[-0.4747195  -0.01038829]
[-0.48547307 -0.01075357]
[-0.49551196 -0.01003889]
[-0.50676125 -0.01124929]
[-0.51813678 -0.01137552]
[-0.53055326 -0.01241649]
[-0.54191759 -0.01136433]
[-0.5531446  -0.01122701]
[-0.56515031 -0.0120057 ]
[-0.57684518 -0.01169487]
[-0.5891424 

[-0.59720005  0.00635396]
[-0.59129855  0.00590149]
[-0.58389279  0.00740576]
[-0.57703729  0.0068555 ]
[-0.57078271  0.00625458]
[-0.56317544  0.00760728]
[-0.55627203  0.0069034 ]
[-0.54812397  0.00814806]
[-0.53879214  0.00933183]
[-0.52834639  0.01044575]
[-0.51886504  0.00948135]
[-0.50841919  0.01044585]
[-0.49808715  0.01033204]
[-0.48894626  0.00914089]
[-0.48106479  0.00788147]
[-0.47350147  0.00756333]
[-0.46631246  0.00718901]
[-0.45955098  0.00676147]
[-0.45326692  0.00628406]
[-0.44650644  0.00676048]
[-0.44131901  0.00518743]
[-0.43774243  0.00357658]
[-0.43480268  0.00293975]
[-0.43152105  0.00328163]
[-0.42792125  0.0035998 ]
[-0.42502922  0.00289203]
[-0.42286574  0.00216348]
[-0.42144631  0.00141943]
[-0.42078108  0.00066522]
[-0.41987482  0.00090626]
[-0.420734   -0.00085917]
[-0.42135247 -0.00061847]
[-0.42372582 -0.00237335]
[-0.42783706 -0.00411124]
[-0.43365668 -0.00581962]
[-0.4391427  -0.00548603]
[-0.4452554  -0.00611269]
[-0.45195027 -0.00669487]
[-0.45817838

[-0.4354792   0.00491241]
[-0.43222001  0.00325918]
[-0.42863762  0.0035824 ]
[-0.42575783  0.00287978]
[-0.42360137  0.00215647]
[-0.42218368  0.00141768]
[-0.42051493  0.00166875]
[-4.20607045e-01 -9.21130565e-05]
[-4.20459364e-01  1.47680649e-04]
[-4.20072945e-01  3.86419274e-04]
[-4.20450547e-01 -3.77602103e-04]
[-0.42258947 -0.00213893]
[-0.42547443 -0.00288496]
[-0.43008473 -0.00461031]
[-0.43638723 -0.0063025 ]
[-0.44333638 -0.00694915]
[-0.45088169 -0.00754531]
[-0.45796807 -0.00708638]
[-0.4665435  -0.00857543]
[-0.47654476 -0.01000126]
[-0.48789776 -0.011353  ]
[-0.500518   -0.01262024]
[-0.51431121 -0.01379321]
Reward 59.0  after  200 episodes
[-0.47552978  0.        ]
[-0.47688905 -0.00135927]
[-0.4775975  -0.00070845]
[-0.47864986 -0.00105236]
[-4.79038316e-01 -3.88458484e-04]
[-4.78759983e-01  2.78332589e-04]
[-0.47781693  0.00094305]
[-0.47721616  0.00060077]
[-0.47796214 -0.00074598]
[-4.78049323e-01 -8.71850665e-05]
[-4.78477066e-01 -4.27743787e-04]
[-4.78242190e-01  2

[-0.48031302 -0.00263115]
[-0.4842679  -0.00395488]
[-0.48851708 -0.00424918]
[-0.49202888 -0.0035118 ]
[-0.4967771  -0.00474822]
[-0.50072627 -0.00394917]
[-0.50484685 -0.00412058]
[-0.50810799 -0.00326114]
[-0.51248528 -0.00437728]
[-0.51594589 -0.00346062]
[-0.5184639  -0.00251801]
[-0.52002042 -0.00155652]
[-0.52260378 -0.00258336]
[-0.5241946  -0.00159082]
[-0.52478095 -0.00058635]
[-0.52635843 -0.00157748]
[-0.52891522 -0.00255679]
[-0.53143214 -0.00251692]
[-0.53489031 -0.00345817]
[-0.53726381 -0.0023735 ]
[-0.53853485 -0.00127104]
[-0.54069391 -0.00215906]
[-0.54272481 -0.0020309 ]
[-0.54561234 -0.00288753]
[-0.54833489 -0.00272255]
[-0.5518721 -0.0035372]
[-0.5551975  -0.00332541]
[-0.55828627 -0.00308877]
[-0.56011536 -0.00182908]
[-0.56167111 -0.00155576]
[-5.61941948e-01 -2.70834684e-04]
[-0.56292584 -0.00098389]
[-0.56461547 -0.00168963]
[-0.56699824 -0.00238278]
[-0.57005644 -0.0030582 ]
[-0.57376734 -0.00371089]
[-0.57610338 -0.00233605]
[-0.57904727 -0.00294389]
[-0.58

[-0.55283823 -0.00102835]
[-0.55464756 -0.00180933]
[-0.55522436 -0.0005768 ]
[-0.55456433  0.00066003]
[-0.55367239  0.00089194]
[-0.5515552   0.00211719]
[-0.54822858  0.00332662]
[-0.54471741  0.00351117]
[-0.54204796  0.00266946]
[-0.5392402   0.00280775]
[-0.53731518  0.00192502]
[-0.53628732  0.00102787]
[-0.53516431  0.00112301]
[-0.53295458  0.00220973]
[-0.53167469  0.00127989]
[-0.53033424  0.00134045]
[-0.52894327  0.00139097]
[-0.52751223  0.00143105]
[-5.27051828e-01  4.60397740e-04]
[-0.52556553  0.0014863 ]
[-0.52306449  0.00250105]
[-0.52056745  0.00249704]
[-0.51909314  0.0014743 ]
[-0.51665263  0.00244051]
[-0.51426421  0.00238842]
[-0.51094579  0.00331842]
[-0.50672225  0.00422355]
[-0.50362522  0.00309703]
[-0.50067791  0.00294731]
[-0.49690236  0.00377554]
[-0.49232683  0.00457553]
[-0.48898549  0.00334134]
[-0.48690329  0.0020822 ]
[-0.48409574  0.00280754]
[-0.48258378  0.00151196]
[-4.82378651e-01  2.05127343e-04]
[-4.82481887e-01 -1.03236275e-04]
[-4.82892719e-

[-6.09090235e-01 -4.31579043e-04]
[-0.60788763  0.0012026 ]
[-0.60705958  0.00082805]
[-0.6046121   0.00244749]
[-0.60156297  0.00304912]
[-0.59793443  0.00362854]
[-0.59375299  0.00418145]
[-0.58904926  0.00470373]
[-0.5828578   0.00619146]
[-0.57722424  0.00563356]
[-0.57019022  0.00703402]
[-0.5638079   0.00638232]
[-0.55612474  0.00768316]
[-0.54919803  0.00692672]
[-0.5430795   0.00611852]
[-0.53581496  0.00726454]
[-0.52845882  0.00735614]
[-0.52006622  0.00839259]
[-0.51170012  0.0083661 ]
[-0.50242324  0.00927688]
[-0.49430507  0.00811817]
[-0.48640632  0.00789875]
[-0.47978594  0.00662038]
[-0.47449321  0.00529273]
[-0.47056743  0.00392577]
[-0.46603772  0.00452971]
[-0.46293757  0.00310015]
[-0.45928988  0.0036477 ]
[-0.45612151  0.00316837]
[-0.45445578  0.00166574]
[-0.45330491  0.00115087]
[-0.45267734  0.00062757]
[-0.45157768  0.00109966]
[-0.45101398  0.0005637 ]
[-0.44999038  0.0010236 ]
[-0.44851436  0.00147602]
[-0.44759673  0.00091763]
[-4.47244188e-01  3.52542701e-

[-0.53777234  0.00755917]
[-0.5301069   0.00766544]
[-0.52139265  0.00871425]
[-0.51169495  0.0096977 ]
[-0.50108651  0.01060844]
[-0.48964679  0.01143973]
[-0.47746126  0.01218553]
[-0.46562066  0.0118406 ]
[-0.45321271  0.01240795]
[-0.44232873  0.01088397]
[-0.43304827  0.00928047]
[-0.42343861  0.00960966]
[-0.4155689   0.00786971]
[-0.4074953  0.0080736]
[-0.40027498  0.00722032]
[-0.39495863  0.00531635]
[-0.38958331  0.00537532]
[-0.38618624  0.00339706]
[-0.38279083  0.00339541]
[-0.38142035  0.00137048]
[-3.81084166e-01  3.36183978e-04]
[-0.38278457 -0.00170041]
[-0.38650996 -0.00372538]
[-0.39223476 -0.00572481]
[-0.3999195  -0.00768473]
[-0.40751069 -0.00759119]
[-0.41595505 -0.00844436]
[-0.42519277 -0.00923773]
[-0.43615787 -0.0109651 ]
[-0.44877128 -0.01261341]
[-0.46194119 -0.01316991]
[-0.47557091 -0.01362971]
[-0.48955958 -0.01398868]
[-0.50380311 -0.01424353]
[-0.51919502 -0.01539191]
[-0.53461995 -0.01542493]
[-0.55096224 -0.01634229]
[-0.56809954 -0.0171373 ]
[-0.58

[-3.60892554e-01 -2.68682976e-04]
[-0.36333365 -0.0024411 ]
[-0.36693096 -0.00359731]
[-0.37166049 -0.00472953]
[-0.3774905  -0.00583002]
[-0.38538158 -0.00789107]
[-0.39327983 -0.00789825]
[-0.40113076 -0.00785093]
[-0.41087968 -0.00974892]
[-0.42145798 -0.01057829]
[-0.43179039 -0.01033242]
[-0.4438027  -0.01201231]
[-0.45740778 -0.01360508]
[-0.47150603 -0.01409825]
[-0.48599339 -0.01448736]
[-0.5017622 -0.0157688]
[-0.51869466 -0.01693246]
[-0.5366639  -0.01796924]
[-0.55353518 -0.01687128]
[-0.57018223 -0.01664706]
[-0.58748105 -0.01729882]
[-0.60430368 -0.01682263]
[-0.61952691 -0.01522324]
[-0.63504058 -0.01551367]
[-0.64973391 -0.01469334]
[-0.66250365 -0.01276974]
[-0.67526149 -0.01275784]
[-0.6869207  -0.01165921]
[-0.69840343 -0.01148272]
[-0.70863438 -0.01023096]
[-0.71754776 -0.00891337]
[-0.72408721 -0.00653945]
[-0.72821204 -0.00412483]
[-0.72989683 -0.0016848 ]
[-0.7291313   0.00076554]
[-0.7259201   0.00321119]
[-0.72128297  0.00463714]
[-0.71424859  0.00703437]
[-0.70

[-0.46893085  0.00972479]
[-0.45861424  0.01031662]
[-0.44778193  0.01083231]
[-0.43751335  0.01026858]
[-0.42688326  0.01063009]
[-0.4179684   0.00891486]
[-0.40883258  0.00913582]
[-0.3995406   0.00929198]
[-0.39215772  0.00738288]
[-0.38473531  0.00742242]
[-0.3783245   0.00641081]
[-0.37196909  0.00635541]
[-0.36671208  0.00525701]
[-0.36158876  0.00512332]
[-0.35663324  0.00495552]
[-0.35187824  0.00475499]
[-0.34835494  0.0035233 ]
[-0.34708625  0.00126869]
[-0.3460804   0.00100585]
[-0.34534389  0.00073651]
[-0.34488147  0.00046242]
[-0.34669613 -0.00181466]
[-0.34877616 -0.00208002]
[-0.35210806 -0.0033319 ]
[-0.35767015 -0.00556209]
[-0.36442595 -0.0067558 ]
[-0.37233069 -0.00790474]
[-0.3823314  -0.01000071]
[-0.39436018 -0.01202878]
[-0.40633414 -0.01197397]
[-0.42016957 -0.01383542]
[-0.43476832 -0.01459875]
[-0.44902545 -0.01425713]
[-0.46483722 -0.01581177]
[-0.48108742 -0.0162502 ]
[-0.4986556  -0.01756818]
[-0.51541067 -0.01675507]
[-0.53222715 -0.01681648]
[-0.54997893

[-0.63126399 -0.00986195]
[-0.64033241 -0.00906843]
[-0.64854312 -0.00821071]
[-0.65583854 -0.00729542]
[-0.66116797 -0.00532943]
[-0.66449467 -0.0033267 ]
[-0.66679584 -0.00230117]
[-6.67055761e-01 -2.59921631e-04]
[-6.67272663e-01 -2.16901730e-04]
[-6.67445066e-01 -1.72403629e-04]
[-6.67571797e-01 -1.26730903e-04]
[-0.66565199  0.00191981]
[-0.66269874  0.00295325]
[-0.65973226  0.00296648]
[-0.65677293  0.00295934]
[-0.65184115  0.00493178]
[-0.6449711   0.00687005]
[-0.63621074  0.00876036]
[-0.62662177  0.00958897]
[-0.61627236  0.0103494 ]
[-0.60423683  0.01203554]
[-0.59260239  0.01163444]
[-0.57945411  0.01314828]
[-0.56688887  0.01256524]
[-0.55299987  0.013889  ]
Reward 59.0  after  200 episodes
[-0.42931072  0.        ]
[-0.43100848 -0.00169777]
[-0.43339178 -0.0023833 ]
[-0.43744341 -0.00405162]
[-0.44313403 -0.00569062]
[-0.44842229 -0.00528826]
[-0.4552696  -0.00684732]
[-0.46162581 -0.0063562 ]
[-0.46844414 -0.00681833]
[-0.47467424 -0.0062301 ]
[-0.48126996 -0.00659572]

In [6]:
env = gym.make('Acrobot-v1')
for _ in range(20):
    obs = env.reset()
    for step in range(100):
        env.render()
        print(obs)
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        if done:
            print("Reward", rewards, " after ", step + 1, "episodes")
            break
env.close()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[ 0.99968084  0.02526313  0.99594133 -0.09000483 -0.03938863  0.09989767]
[ 9.99999991e-01 -1.33074790e-04  9.99681551e-01 -2.52348233e-02
 -2.07263756e-01  5.33583834e-01]
[ 0.99921485 -0.03961922  0.99688172  0.07891027 -0.17644524  0.48463687]
[ 0.99778629 -0.06650206  0.98729271  0.15891228 -0.08504361  0.30378393]
[ 0.99829874 -0.05830628  0.98703713  0.16049206  0.16515406 -0.28611082]
[ 0.99985541 -0.01700449  0.99638351  0.08496998  0.23744493 -0.45562081]
[ 0.99950138  0.03157513  0.99993139 -0.01171399  0.23553089 -0.48798432]
[ 0.99636523  0.08518413  0.99097126 -0.13407447  0.28653235 -0.70960458]
[ 0.99027958  0.13909117  0.96054969 -0.27810841  0.2403601  -0.73018523]
[ 0.9846132   0.17474797  0.91567382 -0.4019222   0.10999977 -0.56147536]
[ 0.98373424  0.17963     0.87851113 -0.47772189 -0.06289973 -0.27021857]
[ 0.99040688  0.13818179  0.88392767 -0.46762365 -0.3477303   

[ 0.99397297  0.1096254   0.98463472 -0.17462668 -0.40077596  0.49888074]
[ 0.99985427  0.01707137  0.99857205 -0.05342147 -0.50435778  0.68651046]
[ 0.9976515  -0.06849438  0.99881646  0.04863821 -0.33153293  0.30394942]
[ 0.99079914 -0.13534054  0.99180679  0.127747   -0.32445776  0.46627066]
[ 0.98166188 -0.1906304   0.97488767  0.22269715 -0.22187753  0.47383764]
[ 0.98132015 -0.1923818   0.97115482  0.23844983  0.20417963 -0.31369201]
[ 0.99017989 -0.13979912  0.98501355  0.17247695  0.31632865 -0.34119811]
[ 0.99820828 -0.05983498  0.99690274  0.0786443   0.46833384 -0.57644167]
[ 0.99969608  0.02465271  0.99995981 -0.00896513  0.35718398 -0.27236688]
[ 0.99708586  0.07628747  0.99976326 -0.02175838  0.14930463  0.15401269]
[0.99544154 0.09537366 0.99983488 0.01817185 0.0397739  0.24117233]
[ 0.99575139  0.09208245  0.9974182   0.07181184 -0.07040039  0.28597927]
[ 0.99660315  0.08235388  0.99563144  0.09337039 -0.02479382 -0.07446294]
[ 0.99659368  0.08246841  0.99908784  0.0427

[ 0.99121334  0.13227287  0.99986789 -0.01625417  0.53772523 -0.9115583 ]
[ 0.97905877  0.20357783  0.99012254 -0.14020472  0.16814443 -0.30172573]
[ 0.98076599  0.1951873   0.99145447 -0.13045315 -0.25128489  0.3964247 ]
[ 0.9924901   0.12232501  0.99970004 -0.0244916  -0.46862092  0.63727978]
[ 0.99950245  0.0315413   0.99719015  0.07491193 -0.42085322  0.32646246]
[ 0.99928176 -0.03789418  0.99538384  0.09597398 -0.25910972 -0.12885696]
[ 0.99669624 -0.08121954  0.99842672  0.05607208 -0.16754919 -0.27081381]
[ 0.99471496 -0.10267494  0.99994473 -0.0105139  -0.04586198 -0.38683099]
[ 0.99501479 -0.09972744  0.99560356 -0.09366722  0.07216642 -0.43115697]
[ 0.99600362 -0.0893129   0.98993914 -0.14149384  0.0291911  -0.04135625]
[ 0.99605876 -0.08869581  0.99402488 -0.1091537  -0.02216927  0.3618791 ]
[ 0.99750711 -0.07056608  0.99749389 -0.07075266  0.20132236  0.02038664]
[ 0.99993388 -0.0114995   0.99510372 -0.09883618  0.37680553 -0.28765145]
[ 0.99732588  0.07308276  0.98437804 -

[ 0.98949331  0.14457869  0.99944602 -0.03328156 -0.0173358  -0.16049543]
[ 0.99067942  0.13621411  0.99664472 -0.08184928 -0.06704299 -0.31877832]
[ 0.9957653   0.09193185  0.99607048 -0.08856406 -0.36949067  0.24509447]
[ 0.999962    0.00871732  0.99966101 -0.02603603 -0.44503463  0.35749902]
[ 0.99792551 -0.0643791   0.99995647  0.0093302  -0.27069244 -0.0207752 ]
[ 0.99548145 -0.0949562   0.9992943  -0.03756202 -0.03171472 -0.4441929 ]
[ 0.99586622 -0.09083207  0.99177744 -0.12797464  0.06940573 -0.44711715]
[ 0.99840917 -0.05638371  0.97050869 -0.24106615  0.26511585 -0.67852066]
[ 0.99995929  0.00902327  0.92607528 -0.3773388   0.37179099 -0.72178254]
[ 0.99641868  0.08455657  0.86877779 -0.49520214  0.36639779 -0.55838365]
[ 0.98896745  0.14813298  0.82575051 -0.56403555  0.25971617 -0.23347643]
[ 0.98313164  0.18289938  0.8220153  -0.56946541  0.08562154  0.17321209]
[ 0.98777083  0.15591274  0.89354296 -0.44897771 -0.35446754  1.21132238]
[ 0.99721226  0.07461705  0.9791544  -

[ 0.99165104 -0.12895043  0.92017324  0.39151144  0.04406071  0.06474533]
[ 0.99515501 -0.09831841  0.93457996  0.35575315  0.25703668 -0.43978692]
[ 0.99983164 -0.01834926  0.97990261  0.19947652  0.52448632 -1.15247606]
[ 0.9962252   0.08680641  0.99915139 -0.04118863  0.49861232 -1.20820933]
[ 0.98568203  0.16861474  0.96676799 -0.25565534  0.30319934 -0.91564397]
[ 0.9798355   0.19980589  0.9242511  -0.38178515  0.00531747 -0.39248196]
[ 0.98543655  0.17004355  0.91679157 -0.39936602 -0.30188166  0.19931657]
[ 0.99515582  0.09831018  0.93900109 -0.34391418 -0.40595163  0.37788151]
[ 0.99987204  0.01599706  0.96386448 -0.26639307 -0.39971732  0.41015189]
[ 0.99776296 -0.06685107  0.98660386 -0.16313437 -0.40946232  0.61708881]
[ 0.99027937 -0.1390927   0.99933174 -0.03655232 -0.29852579  0.62294442]
[ 0.98142525 -0.19184494  0.99427826  0.10682108 -0.22105801  0.77979082]
[ 0.98086796 -0.19467422  0.98134672  0.19224621  0.1945187   0.07100042]
[ 0.98958224 -0.14396874  0.9791109   

[ 0.99947862  0.03228766  0.93995522 -0.34129778  0.6524307  -0.80904407]
[ 0.99106528  0.13337767  0.90940967 -0.41590149  0.34068223  0.02771825]
[ 0.98464296  0.17458021  0.9335796  -0.35837011  0.06903337  0.59302282]
[ 0.98485776  0.17336435  0.97326312 -0.22969303 -0.07667162  0.73132635]
[ 0.98905739  0.14753128  0.99637179 -0.0851073  -0.17465128  0.7043887 ]
[ 0.99540034  0.09580273  0.99740815  0.07195128 -0.3307487   0.83217451]
[ 0.9999474   0.01025693  0.96490506  0.262599   -0.50207989  1.05663985]
[ 0.99767257 -0.06818685  0.91839223  0.39567123 -0.26512228  0.32348341]
[ 0.99321702 -0.11627535  0.89841272  0.43915211 -0.20704273  0.14065579]
[ 0.99258358 -0.12156417  0.92389577  0.38264423  0.15443415 -0.75349766]
[ 0.99832705 -0.05781955  0.98677147  0.16211743  0.46735348 -1.49976506]
[ 0.99919439  0.04013182  0.98933241 -0.14567561  0.48057923 -1.51795619]
[ 0.99094379  0.13427735  0.90070532 -0.43443058  0.4350805  -1.44660918]
[ 0.98167746  0.19055018  0.78429395 -

[ 0.91536458 -0.40262599  0.69799348  0.71610411 -0.56675575  0.25096235]
[ 0.88892504 -0.4580527   0.71819633  0.69584052 -0.03624852 -0.53813573]
[ 0.91467036 -0.40420061  0.84976921  0.5271549   0.62222715 -1.57938233]
[ 0.97188249 -0.23546639  0.98748416  0.1577182   1.11617814 -2.30283327]
[ 0.99983814  0.01799122  0.93920284 -0.34336283  1.36556399 -2.6387041 ]
[ 0.9616993   0.27410667  0.66907412 -0.74319568  1.17038764 -2.1266032 ]
[ 0.89730344  0.44141424  0.41327084 -0.91060816  0.59929188 -0.91669939]
[ 0.87737153  0.47981163  0.38780259 -0.92174245 -0.1740693   0.64060519]
[ 0.91762759  0.39744132  0.584936   -0.81107945 -0.73055208  1.60792207]
[ 0.97635523  0.21617231  0.85591406 -0.51711809 -1.1385595   2.35175099]
[ 0.99875629 -0.04985854  0.99979511  0.02024213 -1.4635402   3.13781353]
[ 0.95404689 -0.29965736  0.84199276  0.53948883 -1.01247474  2.22482629]
[ 0.9961073  -0.08814901  0.99991293 -0.01319563  0.07098133 -0.07364237]
[ 0.99793438 -0.0642415   0.99943191 -

[ 0.9999889  -0.00471154  0.99572169  0.09240299 -0.01152816 -0.06988855]
[ 0.99983831 -0.01798182  0.99467358  0.1030751  -0.11799511  0.17290377]
[ 0.99973352 -0.02308444  0.99600569  0.08928981  0.06733966 -0.30934316]
[ 0.99981256 -0.01936076  0.99859325  0.0530237  -0.03186565 -0.04764926]
[ 0.99996001 -0.00894327  0.99999774  0.00212376  0.13213387 -0.4507906 ]
[ 0.99985677  0.01692458  0.99638535 -0.08494841  0.11860266 -0.40196461]
[ 0.99975131  0.02230056  0.9931217  -0.11708666 -0.0665236   0.0845364 ]
[ 0.99998845  0.00480534  0.99618662 -0.08724807 -0.10393816  0.20751311]
[ 0.99999279 -0.00379772  0.99735208 -0.07272438  0.0199319  -0.06533193]
[ 0.99992426  0.01230742  0.99369303 -0.11213461  0.13641352 -0.32077537]
[ 0.99940477  0.03449801  0.98710899 -0.16004947  0.07974383 -0.15156696]
[ 0.99845025  0.05565159  0.97926958 -0.20256131  0.12629417 -0.26990413]
[ 0.99661862  0.08216647  0.96552001 -0.26032885  0.13229908 -0.3098212 ]
[ 0.99442249  0.10546995  0.94859731 -

[ 0.99529228  0.09691889  0.9994411   0.03342894  0.17064684 -0.27689784]
[ 0.99135956  0.13117249  0.99886077 -0.04771961  0.16461286 -0.51540709]
[ 0.99124776  0.13201472  0.99549375 -0.09482718 -0.15722571  0.05038779]
[ 0.99745971  0.07123287  0.99954784 -0.0300686  -0.43921485  0.57762882]
[ 0.99940069 -0.03461594  0.99251045  0.12215978 -0.59327705  0.9037855 ]
[ 0.98819875 -0.15317711  0.9521007   0.30578467 -0.56830202  0.92811942]
[ 0.96880203 -0.2478359   0.88964525  0.4566523  -0.37532902  0.66796096]
[ 0.95629399 -0.29240692  0.84406538  0.53624027 -0.07738911  0.23178371]
[ 0.96443892 -0.26430583  0.86216559  0.50662658  0.363566   -0.57079939]
[ 0.98555234 -0.16937114  0.92870463  0.37082033  0.5866403  -0.90701399]
[ 0.99902017 -0.04425729  0.98254404  0.18603011  0.64132003 -0.9686561 ]
[ 0.99504105  0.09946508  0.99855048 -0.05382316  0.76057643 -1.37549392]
[ 0.97050863  0.24106638  0.94509739 -0.32678882  0.63947643 -1.3437052 ]
[ 0.95029726  0.31134404  0.87754621 -

[ 0.98707969 -0.1602301   0.94433546  0.3289841  -0.4004894   1.05342975]
[ 0.98040479 -0.19699355  0.89833456  0.43931197  0.0347642   0.12354595]
[ 0.98718625 -0.15957225  0.91434892  0.40492723  0.3369773  -0.49196393]
[ 0.99659352 -0.08247031  0.95504586  0.2964581   0.42116784 -0.63692803]
[ 0.99991678  0.01290057  0.98993192  0.14154432  0.50961384 -0.91146388]
[ 0.99234355  0.12350822  0.99691362 -0.07850625  0.56977296 -1.23807201]
[ 0.97972555  0.20034431  0.9663756  -0.25713459  0.18917383 -0.53674061]
[ 0.97559708  0.21956851  0.93875694 -0.34458006  0.00109478 -0.3630785 ]
[ 0.98229384  0.18734675  0.93337943 -0.35889113 -0.32346031  0.20732041]
[ 0.99642367  0.08449778  0.97105771 -0.23884498 -0.69142126  1.01784238]
[ 0.99883186 -0.04832089  0.99875676 -0.04984917 -0.60479044  0.8403223 ]
[ 0.98532693 -0.17067758  0.9897407   0.1428753  -0.59573147  1.03851778]
[ 0.96267436 -0.27066229  0.94166466  0.33655264 -0.40355574  0.91194378]
[ 0.95181802 -0.30666343  0.89666297  

[ 0.99468436  0.10297102  0.99990551 -0.01374696 -0.05619803  0.38997251]
[ 0.99776468  0.06682544  0.99435546  0.10610002 -0.29498549  0.78328862]
[ 0.99983092  0.0183885   0.97662948  0.2149299  -0.17742921  0.29511786]
[ 0.99990666 -0.0136628   0.96836277  0.24954667 -0.13571978  0.05027032]
[ 0.99891512 -0.04656815  0.96426647  0.26493427 -0.18627139  0.10103176]
[ 0.99640221 -0.08475038  0.95856462  0.2848752  -0.18804153  0.09703887]
[ 0.99573758 -0.09223166  0.97234252  0.23355948  0.11319737 -0.62106125]
[ 0.9976249  -0.06888076  0.99307031  0.11752171  0.11244068 -0.5342471 ]
[ 0.99970707 -0.0242026   0.9992999  -0.03741258  0.3205008  -0.98350269]
[ 0.99969047  0.02487907  0.98216627 -0.18801442  0.15628209 -0.50124288]
[ 0.99885977  0.04774053  0.96553193 -0.26028463  0.06608616 -0.2253775 ]
[ 0.99803058  0.06272925  0.95255245 -0.30437449  0.07966549 -0.22433847]
[ 0.99789759  0.06481053  0.95064779 -0.3102721  -0.05915993  0.16322132]
[ 0.9991867   0.04032293  0.96973209 -

[ 0.94645426  0.32283795  0.95714259 -0.28961709 -0.2574909   0.90821257]
[ 0.96923886  0.246122    0.99555149 -0.09421903 -0.52052131  1.04067362]
[ 0.99299196  0.1181819   0.99081999  0.13518783 -0.74784913  1.19786107]
[ 0.99884443 -0.04806051  0.92431855  0.38162182 -0.87542441  1.28924139]
[ 0.97710214 -0.2127708   0.8123187   0.58321379 -0.75006887  0.96400318]
[ 0.94830091 -0.31737263  0.746781    0.66507002 -0.31424779  0.06315338]
[ 0.94044874 -0.33993553  0.78007879  0.6256813   0.07959837 -0.57538571]
[ 0.96101443 -0.27649823  0.891129    0.45375005  0.57313442 -1.44391832]
[ 0.99333959 -0.1152235   0.99627662  0.0862142   1.02977033 -2.31612108]
[ 0.99673193  0.08078026  0.94334656 -0.33180909  0.87819145 -1.81960455]
[ 0.97633944  0.21624363  0.82087332 -0.57111031  0.46422558 -0.82710211]
[ 0.96338239  0.26813126  0.7713637  -0.63639456  0.06056274  0.02122118]
[ 0.97108636  0.23872849  0.82602436 -0.56363441 -0.3585696   0.87627095]
[ 0.99266893  0.12086519  0.95003157 -

[ 0.91203559  0.41011107  0.63342    -0.77380818  1.12727874 -1.0276588 ]
[ 0.83690197  0.5473528   0.5685282  -0.82266377  0.41103792  0.22684209]
[ 0.84275665  0.53829473  0.72252809 -0.69134156 -0.52376809  1.79284826]
[ 0.93059138  0.36605966  0.966347   -0.25724206 -1.37010068  3.15870688]
[ 0.99782824  0.06586959  0.92023996  0.39135459 -1.62045905  3.26606728]
[ 0.97203201 -0.23484839  0.56155721  0.82743791 -1.34731178  2.3492135 ]
[ 0.89336106 -0.44933953  0.22241014  0.97495319 -0.908296    1.33717104]
[ 0.83617209 -0.54846717  0.09316789  0.99565041 -0.22033889 -0.03046094]
[ 0.84757013 -0.5306834   0.2101817   0.97766234  0.43263573 -1.15365022]
[ 0.92108129 -0.38937032  0.54875357  0.83598416  1.14762835 -2.52772695]
[ 0.9949509  -0.1003629   0.94532964  0.32611636  1.78608299 -3.94297515]
[ 0.96733972  0.25348347  0.8945289  -0.44701013  1.65616454 -3.75691702]
[ 0.86657369  0.49904913  0.45871799 -0.88858191  0.95759442 -2.47047291]
[ 0.80154209  0.59793835  0.10098353 -

[ 0.83812136 -0.54548381  0.42293853  0.90615837  0.05056081 -0.538608  ]
[ 0.87717456 -0.48017163  0.60226566  0.79829573  0.70049366 -1.54302726]
[ 0.99690666  0.07859461  0.999385    0.03506594 -0.01237997  0.06307492]
[ 0.99853011  0.05419977  0.99638414  0.08496258 -0.22528423  0.42384484]
[ 0.9999785   0.00655752  0.98696503  0.16093485 -0.2394732   0.32155418]
[ 0.99875154 -0.04995355  0.97128301  0.23792711 -0.31183889  0.4418648 ]
[ 0.99374133 -0.1117057   0.94658486  0.3224548  -0.29276277  0.41496645]
[ 0.99083145 -0.13510382  0.94597757  0.32423208  0.06148799 -0.3990936 ]
[ 0.99340433 -0.11466402  0.97098176  0.23915354  0.13767474 -0.46998603]
[ 0.99834705 -0.05747318  0.99662739  0.08206001  0.42017832 -1.08811368]
[ 0.99954515  0.0301578   0.99036529 -0.13847954  0.43113439 -1.06964548]
[ 0.99304825  0.11770803  0.9363155  -0.35115993  0.42207131 -1.07746911]
[ 0.98652441  0.16361414  0.88481837 -0.4659361   0.03199954 -0.16063274]
[ 0.98981401  0.14236653  0.8986471  -

[ 0.99818498  0.06022255  0.93499088 -0.35467177 -0.74320962  1.42494021]
[ 0.99664806 -0.08180859  0.99666506 -0.08160118 -0.63993226  1.31073391]
[ 0.98361484 -0.1802827   0.99104983  0.13349244 -0.32711759  0.79266062]
[ 0.97896168 -0.20404419  0.97576921  0.21880231  0.09138284  0.05808929]
[ 0.98735993 -0.15849405  0.9817505   0.19017347  0.36149877 -0.33871986]
[ 0.99852621 -0.05427157  0.99821936  0.05964981  0.6619247  -0.93935876]
[ 0.99783336  0.06579203  0.9955609  -0.09411959  0.51045569 -0.55479777]
[ 0.9861772   0.16569411  0.97671135 -0.21455754  0.47167923 -0.62848931]
[ 0.97608512  0.21738867  0.96544707 -0.26059923  0.04406579  0.16791375]
[ 0.98071919  0.19542227  0.98303291 -0.18342925 -0.26167512  0.60728918]
[ 0.99280006  0.1197833   0.99949146 -0.03188751 -0.48419072  0.88056437]
[ 9.99999999e-01  3.35178918e-05  9.83240877e-01  1.82311214e-01
 -6.84269385e-01  1.21363787e+00]
[ 0.99035986 -0.13851841  0.91022483  0.41411443 -0.67023487  1.15960712]
[ 0.97078038 

[0.99971121 0.02403105 0.99846291 0.055424   0.01888406 0.12843368]
[ 0.99991961  0.01267974  0.9938342   0.11087644 -0.12810285  0.41623427]
[ 0.99999724  0.00235078  0.98932815  0.14570452  0.02757325 -0.07183029]
[ 0.99995083  0.00991617  0.9930719   0.11750831  0.04567869 -0.20655989]
[ 0.99981232  0.01937305  0.99775621  0.06695187  0.0454372  -0.29106264]
[ 0.99991093  0.01334658  0.99918966  0.0402495  -0.10512795  0.02696141]
[ 0.99998426  0.00561056  0.99997121  0.0075875   0.02812219 -0.34885465]
[ 0.99994992  0.01000783  0.99821171 -0.05977772  0.01286443 -0.31287176]
[ 0.99973654  0.02295343  0.98918407 -0.14667951  0.11093708 -0.54347535]
[ 0.99969089  0.02486222  0.98004355 -0.19878289 -0.09314415  0.02244935]
[ 0.99990788  0.01357307  0.97850055 -0.2062442  -0.0178135  -0.09893321]
[ 0.99984157  0.01780009  0.9716748  -0.23632197  0.05819782 -0.20345096]
[ 0.99937339  0.03539541  0.95949277 -0.28173324  0.11280482 -0.25604778]
[ 0.99887274  0.04746842  0.95460452 -0.2978

[ 0.99999655 -0.00262866  0.98971215  0.14307292 -0.87744846  1.76815066]
[ 0.98847615 -0.15137669  0.90954076  0.41561473 -0.57988668  1.01704963]
[ 0.96913083 -0.24654702  0.82638707  0.56310248 -0.36955428  0.64152427]
[ 0.9573406  -0.28896189  0.78090752  0.62464665 -0.0617227   0.11007457]
[ 0.96930944 -0.24584388  0.83823161  0.54531438  0.50117243 -1.07574537]
[ 0.99496994 -0.10017392  0.96698538  0.25483184  0.9452542  -2.0519717 ]
[ 0.99405105  0.10891513  0.97927177 -0.20255075  1.08658836 -2.43881032]
[ 0.95310798  0.30263044  0.78729682 -0.61657418  0.84267839 -2.06013037]
[ 0.91340058  0.40706189  0.56639274 -0.82413547  0.25909217 -0.95326505]
[ 0.91309056  0.40775682  0.48026616 -0.8771228  -0.24861896 -0.05399639]
[ 0.95129181  0.3082919   0.57108366 -0.82089187 -0.79836351  1.10884778]
[ 0.99380146  0.11116946  0.80378408 -0.59492112 -1.18500196  2.09875786]
[ 0.99189571 -0.12705471  0.98180133 -0.18991091 -1.14064139  2.24509959]
[ 0.94969501 -0.3131763   0.97809232  

[ 0.96857032  0.2487399   0.98624539 -0.16528771  0.24814675 -1.09312655]
[ 0.96868748  0.24828325  0.95483689 -0.29713045 -0.25523531 -0.24348147]
[ 0.98626204  0.16518835  0.95626289 -0.29250861 -0.57689189  0.27896279]
[ 0.9998544   0.01706409  0.98618896 -0.16562409 -0.87811216  0.98183929]
[ 0.98796753 -0.15466141  0.99931842  0.03691466 -0.80398186  0.98765737]
[ 0.95475727 -0.29738621  0.97174987  0.23601311 -0.62744433  0.96910115]
[ 0.92341227 -0.38380957  0.91940212  0.39331887 -0.27052862  0.65340241]
[ 0.92414179 -0.38204968  0.8978228   0.44035692  0.28941506 -0.14172802]
[ 0.9603221  -0.27889328  0.9389419   0.34407573  0.78121131 -0.87812496]
[ 0.99564449 -0.09323118  0.99236991  0.12329627  1.06727946 -1.33208694]
[ 0.99070775  0.1360079   0.98340223 -0.18143886  1.17314597 -1.63349577]
[ 0.93867411  0.34480561  0.88233783 -0.47061658  0.93194076 -1.35998253]
[ 0.8868892   0.4619822   0.78424748 -0.62044813  0.32611701 -0.40326143]
[ 0.88808764  0.45967417  0.79837695 -

In [7]:
env = gym.make('Pendulum-v0')
for _ in range(20):
    obs = env.reset()
    for step in range(100):
        env.render()
        print(obs)
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        if done:
            print("Reward", rewards, " after ", step + 1, "episodes")
            break
env.close()

[ 0.62559016  0.78015187 -0.52171758]
[0.61256005 0.79042405 0.33184804]
[0.56639326 0.82413511 1.14345057]
[0.48866908 0.87246922 1.83118433]
[0.36724434 0.93012451 2.69038059]
[0.21369438 0.97690056 3.21378926]
[0.00681099 0.9999768  4.17088198]
[-0.24764755  0.96885019  5.14124909]
[-0.51077767  0.85971284  5.71675409]
[-0.75418838  0.65665812  6.36656271]
[-0.93570892  0.35277304  7.11692086]
[-0.99990317 -0.01391605  7.48899064]
[-0.92389458 -0.3826471   7.57486506]
[-0.72563007 -0.68808502  7.3237385 ]
[-0.46044902 -0.88768615  6.66897367]
[-0.16325404 -0.98658407  6.29025828]
[ 0.11171954 -0.99373978  5.51882602]
[ 0.33817109 -0.94108465  4.66039124]
[ 0.52231132 -0.85275488  4.09172619]
[ 0.6634335  -0.74823526  3.51678291]
[ 0.76332585 -0.64601366  2.86095125]
[ 0.83126618 -0.55587457  2.25871597]
[ 0.87474403 -0.48458527  1.67051405]
[ 0.89905908 -0.43782733  1.05416696]
[ 0.9158729  -0.40146834  0.801223  ]
[ 0.9256893  -0.3782847   0.50353793]
[ 0.92683376 -0.37547195  0.06

[-0.82496739  0.56518033 -3.51629024]
[-0.72491712  0.68883609 -3.1846084 ]
[-0.62813522  0.7781042  -2.63519518]
[-0.54724209  0.83697437 -2.00177467]
[-0.49636979  0.86811119 -1.19307133]
[-0.46343507  0.88613088 -0.75088498]
[-0.46867571  0.8833703   0.11846562]
[-0.50854059  0.86103802  0.91395904]
[-0.56259678  0.82673143  1.28068961]
[-0.64005346  0.76833038  1.94088729]
[-0.72170727  0.69219839  2.23395533]
[-0.80980168  0.5867037   2.75096809]
[-0.89406801  0.44793124  3.25064374]
[-0.96075804  0.27738778  3.66751999]
[-0.99722692  0.07442086  4.13168803]
[-0.9917171  -0.12844137  4.06573788]
[-0.94355083 -0.33122776  4.17614638]
[-0.8615114  -0.50773823  3.89905829]
[-0.75609    -0.65446765  3.61841853]
[-0.63784839 -0.77016196  3.31233384]
[-0.52118978 -0.85344081  2.86913708]
[-0.41498527 -0.90982813  2.40635681]
[-0.33126621 -0.94353733  1.80562742]
[-0.2703178  -0.96277115  1.27844278]
[-0.23151478 -0.97283139  0.8017725 ]
[-0.21617435 -0.97635478  0.31480027]
[-0.24151921

[-0.7074903  -0.70672306  2.94011986]
[-0.61159167 -0.79117358  2.55739749]
[-0.53188076 -0.84681926  1.94501631]
[-0.48111535 -0.8766573   1.17786897]
[-0.47035122 -0.88247931  0.24475642]
[-0.48400678 -0.87506425 -0.31078124]
[-0.53482786 -0.84496104 -1.18152456]
[-0.61017847 -0.79226399 -1.83963656]
[-0.69826789 -0.71583654 -2.33378182]
[-0.78628249 -0.61786717 -2.63588283]
[-0.87061564 -0.49196383 -3.03366502]
[-0.94416549 -0.32947158 -3.57200309]
[-0.98964844 -0.14351292 -3.83467338]
[-0.99884454  0.04805811 -3.84173603]
[-0.96952748  0.24498258 -3.98850193]
[-0.90864248  0.41757496 -3.66546193]
[-0.8306768   0.55675493 -3.19398617]
[-0.74609448  0.6658401  -2.76290236]
[-0.67411436  0.73862699 -2.04824154]
[-0.6105807   0.79195404 -1.65942739]
[-0.56847636  0.8226996  -1.04281936]
[-0.56066432  0.82804319 -0.18929616]
[-0.58339233  0.81219049  0.55422714]
[-0.63674844  0.77107161  1.34749459]
[-0.70201762  0.71215958  1.7590541 ]
[-0.78025209  0.62546517  2.33684214]
[-0.85734382

[-0.93636778  0.3510205  -0.97940941]
[-0.92517051  0.37955174 -0.61302013]
[-0.91448287  0.40462461 -0.54513123]
[-0.90983708  0.41496564 -0.22673478]
[-0.91206038  0.41005593  0.10779295]
[-0.92511119  0.3796963   0.66094797]
[-0.94168837  0.33648628  0.92569781]
[-0.9562394   0.29258541  0.92507305]
[-0.96883179  0.24771954  0.93207448]
[-0.97983461  0.19981024  0.98322932]
[-0.99082833  0.13512665  1.31245941]
[-0.99739487  0.07213511  1.26686939]
[-0.99999589  0.0028664   1.3866283 ]
[-0.99854646 -0.05389783  1.13580711]
[-0.99502835 -0.09959213  0.916671  ]
[-0.98944359 -0.14491853  0.91346259]
[-0.984967   -0.17274263  0.56365694]
[-0.97971044 -0.20041819  0.56342552]
[-0.97569772 -0.21912088  0.382572  ]
[-0.97474675 -0.22331319  0.0859765 ]
[-0.97312709 -0.23026868  0.14283176]
[-0.97226814 -0.23386889  0.07402515]
[-0.97635104 -0.21619121 -0.3628659 ]
[-0.98070371 -0.19549994 -0.42289073]
[-0.98734764 -0.15857062 -0.75048813]
[-0.99177063 -0.1280274  -0.61726075]
[-0.99661299

[-0.68666499 -0.72697399  3.4106002 ]
[-0.57913305 -0.81523304  2.78453382]
[-0.48373845 -0.87521261  2.25487355]
[-0.412889   -0.91078135  1.58594756]
[-0.36639911 -0.93045779  1.00975509]
[-0.33783889 -0.94120395  0.61032395]
[-0.35420039 -0.93516955 -0.34878103]
[-0.39567042 -0.91839257 -0.89477688]
[-0.45863061 -0.88862701 -1.3931166 ]
[-0.55300521 -0.8331778  -2.190266  ]
[-0.6698967  -0.74245431 -2.96205571]
[-0.79059112 -0.61234441 -3.55408187]
[-0.89818574 -0.43961616 -4.07702613]
[-0.97249829 -0.23291003 -4.40204681]
[-9.99997072e-01  2.41999914e-03 -4.74977880e+00]
[-0.97133698  0.23770668 -4.75168352]
[-0.89636669  0.44331339 -4.38575205]
[-0.7958001   0.60555941 -3.82353696]
[-0.97229785 -0.23374536 -0.43677467]
[-0.98027114 -0.19765751 -0.73920541]
[-0.98628785 -0.16503415 -0.66350148]
[-0.99231373 -0.12374759 -0.83454034]
[-0.99757526 -0.06959598 -1.08826671]
[-0.99999861 -0.00166702 -1.35970532]
[-0.99862058  0.05250654 -1.08395427]
[-0.99314928  0.11685246 -1.29178687]


[0.81597934 0.57808106 0.83627911]
[0.77467615 0.63235818 1.36437013]
[0.70657781 0.70763536 2.03104878]
[0.60639706 0.795162   2.66257439]
[0.4706399  0.88232539 3.2301153 ]
[0.29753572 0.95471069 3.75810894]
[0.09160671 0.99579527 4.20750223]
[-0.14965586  0.98873815  4.83911043]
[-0.40377658  0.91485762  5.30841913]
[-0.65431019  0.75622627  5.95257859]
[-0.85782957  0.51393427  6.35522824]
[-0.9807322   0.195357    6.86286751]
[-0.98944032 -0.14494083  6.84149236]
[-0.89177858 -0.45247207  6.48164584]
[-0.70610495 -0.7081072   6.34557016]
[-0.48508195 -0.87446869  5.55050948]
[-0.25146658 -0.96786598  5.04523304]
[-0.02534308 -0.99967881  4.57698876]
[ 0.15361885 -0.98813018  3.59150712]
[ 0.29412517 -0.95576691  2.88621025]
[ 0.39453443 -0.91888116  2.14042109]
[ 0.46805228 -0.88370078  1.63048625]
[ 0.51342853 -0.85813236  1.04179867]
[ 0.52476034 -0.85125001  0.26516347]
[ 0.49585048 -0.86840791 -0.67239263]
[ 0.43686902 -0.89952513 -1.33397793]
[ 0.35555444 -0.93465557 -1.77215

[ 0.75509126 -0.6556197  -2.19585097]
[ 0.66689495 -0.74515175 -2.51518668]
[ 0.5391853  -0.84218716 -3.21129065]
[ 0.37715306 -0.92615094 -3.65498057]
[ 0.15400267 -0.98807043 -4.64204826]
[-0.12492584 -0.99216608 -5.59742176]
[-0.41648117 -0.90914434 -6.08636591]
[-0.69532398 -0.71869643 -6.78598421]
[-0.91218993 -0.40976765 -7.59452795]
[-0.99953735 -0.03041526 -7.83558774]
[-0.93454438  0.35584659 -7.88479496]
[-0.7268599   0.68678576 -7.86475741]
[-0.42747162  0.90402877 -7.44089059]
[-0.1067795   0.99428273 -6.69421336]
[ 0.18552917  0.98263876 -5.8718762 ]
[ 0.41845914  0.90823562 -4.90275532]
[ 0.59964054  0.80026947 -4.22607495]
[ 0.74210365  0.67028514 -3.86303017]
[ 0.84990901  0.52692947 -3.59218445]
[ 0.92390273  0.38262743 -3.24690536]
[ 0.97246744  0.2330388  -3.1487421 ]
[ 0.99509046  0.09896954 -2.7213907 ]
[ 0.99912383 -0.04185178 -2.8199166 ]
[ 0.98235415 -0.18703026 -2.92548357]
[ 0.94240247 -0.33448108 -3.05832714]
[ 0.87196139 -0.48957465 -3.41094661]
[ 0.76768832

[ 0.2088827  -0.9779407   4.46837903]
[ 0.38314437 -0.92368847  3.65531467]
[ 0.50769943 -0.86153426  2.78628643]
[ 0.59726202 -0.80204618  2.15141284]
[ 0.66368915 -0.7480085   1.71313966]
[ 0.69774476 -0.71634645  0.9300882 ]
[ 0.72186109 -0.69203798  0.68486903]
[ 0.72689739 -0.68674609  0.14610757]
[ 0.71981525 -0.69416569 -0.20514198]
[ 0.69096297 -0.72289016 -0.81431644]
[ 0.64010906 -0.76828405 -1.36360199]
[ 0.57417439 -0.81873303 -1.66089648]
[ 0.48254313 -0.87587221 -2.16078896]
[ 0.3414328  -0.93990619 -3.10230119]
[ 0.1494765  -0.98876528 -3.96804154]
[-0.09253159 -0.99570975 -4.85405905]
[-0.35128106 -0.93627006 -5.32549721]
[-0.60696568 -0.79472804 -5.86595854]
[-0.82487342 -0.56531748 -6.3548262 ]
[-0.9691675  -0.24640283 -7.03702387]
[-0.99469916  0.1028279  -7.03953727]
[-0.89575014  0.44455785 -7.15341239]
[-0.68789108  0.72581393 -7.03072572]
[-0.43075272  0.90247    -6.26505533]
[-0.15049371  0.98861097 -5.88518054]
[ 0.11893785  0.9929017  -5.40575438]
[ 0.33319651

[-0.77303231  0.63436666 -5.68447251]
[-0.59287056  0.80529777 -4.97977196]
[-0.39169523  0.92009502 -4.64290914]
[-0.21457549  0.97670741 -3.72432308]
[-0.05700545  0.99837387 -3.18441613]
[ 0.05705551  0.99837101 -2.28245749]
[ 0.13141432  0.99132753 -1.49418056]
[ 0.17346026  0.98484087 -0.85093147]
[0.16543775 0.98622023 0.16280501]
[0.11060857 0.99386405 1.10733017]
[0.02462973 0.99969664 1.72406253]
[-0.090018    0.99594014  2.29544491]
[-0.23578837  0.97180443  2.95779433]
[-0.40531703  0.91417619  3.58591714]
[-0.5816013   0.81347399  4.0674036 ]
[-0.76283958  0.64658779  4.93995364]
[-0.91299538  0.4079699   5.65746947]
[-0.99386666  0.11058506  6.1883539 ]
[-0.97978262 -0.20006501  6.24471949]
[-0.87036865 -0.49240065  6.26843081]
[-0.69266919 -0.72125542  5.81534491]
[-0.47119502 -0.88202906  5.49076262]
[-0.23477758 -0.97204912  5.07310781]
[-0.01863612 -0.99982633  4.36705093]
[ 0.16080639 -0.98698597  3.60289652]
[ 0.30088588 -0.95366015  2.88227648]
[ 0.7115285  -0.70265

[-0.97389714 -0.22698977  2.21922191]
[-0.94969013 -0.31319108  1.79131299]
[-0.92776802 -0.37315746  1.27717376]
[-0.90451495 -0.42644192  1.16290861]
[-0.88080433 -0.47348045  1.05365252]
[-0.86499772 -0.50177578  0.64824888]
